### ISSUE TITLE
Create onboarding page on website

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/opensandiego.github.io#69] opened 2020-03-10 18:18 UTC
Work with Marissa to create links and items for onboarding page.

When complete send Nancy link for onboarding URL so she can integrate with slackbot

**Comment by nikolajbaer** [comment] 2020-04-29 02:36
This is actually a duplicate of #50 so i am going to close this and work off the other issue

**Closed by nikolajbaer** 2020-04-29 02:36 UTC
